apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: rahul29d/aks
        ports:
        - containerPort: 3000

