apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000 # Port exposed by the service
      targetPort: 3000 # Port on which the backend container is listening
      nodePort: 30080 # NodePort number (use any available port, e.g., 30080)
