apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 5173 # Port exposed by the service
      targetPort: 5173 # Port on which the frontend container is listening
      nodePort: 30081 # NodePort number (use any available port, e.g., 30081)
