apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-backend-image:tag
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://ati:ati12345@mongodb:27017/your-database-name"
