apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: 3tier
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rahul29d/3-tier-backend
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB
          value: "mongodb://ati:ati12345@mongodb:27017/admin"
