apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: 3tier
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3500
  type: LoadBalancer
