apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: 3tier
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: your-frontend-image:tag
        ports:
        - containerPort: 5173
        env:
        - name: VITE_BASE_URL
          value: "http://backend:3000"
