apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: your-namespace-name
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer
